#!/bin/bash
# referred from https://github.com/HuffordLab/NAM-genomes/tree/master/te-annotation
# use EDTA to conduct final TE annotation for each genome
genome="$1" # genome fasta
RM_out="$2" # generated by Mod_RM.sh
cds="$3" # cds fasta
echo $genome
echo $RM_out 
echo $cds
lib=/data/yjwang/Genomics-Analysis/NAM_anno_module/final_TE/make_pan_TE_lib/QIN.PAN-TElib.fa
/data/yjwang/anaconda3/envs/EDTA/bin/perl /data/yjwang/Genomics-Analysis/TE/EDTA-1.9.0/EDTA.pl \
   --genome ${genome} \
   --species Maize \
   -t 16 \
   --step final \
   --anno 1 \
   --rmout ${RM_out} \
   --curatedlib ${lib} \
   --cds ${cds}
